name: check_darn
description: แอพพลิเคชั่นเช็กด่านและรายงานเหตุการณ์แบบเรียลไทม์
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^4.0.0
  
  # Internationalization
  intl: ^0.20.2
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.0
  firebase_messaging: ^16.0.0
  cloud_functions: ^6.0.0
  google_sign_in: ^6.2.1
  
  # Maps & Location
  location: ^8.0.1
  geolocator: ^14.0.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_cache: ^2.0.0+1
  sensors_plus: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.5
  cached_network_image: ^3.3.1  # เพิ่มสำหรับ cache รูปภาพ
  dotted_border: ^2.1.0
  popover: ^0.3.1  # เพิ่ม popover package
  
  # HTTP requests
  http: ^1.5.0-beta.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.1.12
  flutter_svg: ^2.0.7
  flutter_compass: ^0.8.0
  audioplayers: ^6.5.0
  flutter_tts: ^4.2.3
  connectivity_plus: ^6.1.4
  crypto: ^3.0.6
  geocoding: ^4.0.0
  wakelock_plus: ^1.2.8
  device_info_plus: ^11.1.0
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/icons/bottom_bar/
    - assets/icons/report_screen/
    - assets/icons/speed_camera_screen/
    - assets/icons/location_picker_screen/
    - assets/sounds/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sarabun-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sarabun-Bold.ttf
          weight: 700
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Medium.ttf
          weight: 500
