name: check_darn
description: A real-time incident reporting Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.5
  
  # Maps & Location
  location: ^5.0.3
  geolocator: ^10.1.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_cache: ^1.0.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1  # เพิ่มสำหรับ cache รูปภาพ
  dotted_border: ^2.1.0
  
  # HTTP requests
  http: ^1.5.0-beta.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.12
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/map_tiles/
    - assets/icons/bottom_bar/
    - assets/icons/bottom_bar/report_screen/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sarabun-Bold.ttf
          weight: 700
